# Generated by Django 4.2.10 on 2026-02-13 14:17

import core.encryption
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nid_number', core.encryption.EncryptedCharField(blank=True, help_text='Rwanda National ID (encrypted)', max_length=2000, null=True)),
                ('tax_id', core.encryption.EncryptedCharField(blank=True, help_text='TIN - Tax Identification Number (encrypted)', max_length=2000, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('user_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin'), ('GOV_OFFICIAL', 'Government Official')], default='CUSTOMER', max_length=15)),
                ('is_verified', models.BooleanField(default=False, help_text='KYC verification status')),
                ('verification_date', models.DateTimeField(blank=True, help_text='When KYC was completed', null=True)),
                ('assigned_sector', models.CharField(blank=True, help_text='For Agents: assigned 416 sector', max_length=100, null=True)),
                ('birth_year', models.IntegerField(blank=True, help_text='Year of birth for NID cross-validation', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(default='1.0', max_length=10)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ZONE_1', 'Kigali'), ('ZONE_2', 'Provinces'), ('ZONE_3', 'EAC Countries')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'shipping_zones',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Account Registration'), ('LOGIN', 'Login Verification'), ('PASSWORD_RESET', 'Password Reset'), ('TRANSACTION', 'Transaction Confirmation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'is_used', 'expires_at'], name='otp_verific_phone_2ee5cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShippingTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tariff name/description', max_length=100)),
                ('transport_type', models.CharField(choices=[('MOTO', 'Motorcycle'), ('BUS', 'Bus'), ('TRUCK', 'Truck')], max_length=10)),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_kg_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.shippingzone')),
            ],
            options={
                'db_table': 'shipping_tariffs',
                'ordering': ['transport_type', 'min_weight_kg'],
                'unique_together': {('transport_type', 'zone', 'min_weight_kg')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('SECTOR', 'Sector')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.location')),
            ],
            options={
                'db_table': 'locations',
                'unique_together': {('name', 'location_type', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(help_text='Cached phone for deleted users', max_length=20)),
                ('user_type', models.CharField(max_length=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export')], max_length=10)),
                ('resource_type', models.CharField(help_text="e.g., 'shipment', 'user'", max_length=50)),
                ('resource_id', models.CharField(help_text='ID of accessed resource', max_length=100)),
                ('endpoint', models.CharField(help_text='API endpoint accessed', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_method', models.CharField(max_length=10)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_verified'], name='users_user_ty_bbd6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['assigned_sector'], name='users_assigne_6693eb_idx'),
        ),
    ]
