# Generated by Django 4.2.10 on 2026-02-13 14:42

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid_number',
            field=core.encryption.EncryptedCharField(blank=True, help_text='Rwanda National ID (encrypted)', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tax_id',
            field=core.encryption.EncryptedCharField(blank=True, help_text='TIN - Tax Identification Number (encrypted)', max_length=2000, null=True),
        ),
    ]
