# Generated by Django 4.2.10 on 2026-02-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_type', models.CharField(choices=[('MOTO', 'Motorcycle'), ('BUS', 'Bus')], default='MOTO', max_length=10)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domestic_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='domestic.domesticshipment')),
            ],
            options={
                'db_table': 'shipment_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
