# Generated by Django 4.2.10 on 2026-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0002_domesticshipment_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticshipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_PAYMENT', 'Pending Payment'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ASSIGNED', 'Assigned'), ('DELIVERED', 'Delivered'), ('PAYMENT_FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
