# Generated by Django 4.2.10 on 2026-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub_location', models.CharField(max_length=200)),
                ('total_shipments', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'shipment_manifests',
                'ordering': ['-created_at'],
            },
        ),
    ]
