# Generated by Django 4.2.10 on 2026-02-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.CharField(choices=[('UGANDA', 'Uganda'), ('KENYA', 'Kenya'), ('DRC', 'Democratic Republic of Congo'), ('TANZANIA', 'Tanzania'), ('BURUNDI', 'Burundi')], max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_address', models.TextField()),
                ('customs_declaration', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('AT_CUSTOMS', 'At Customs'), ('CLEARED_CUSTOMS', 'Cleared Customs')], default='PENDING', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'international_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('TIN', 'Tax Identification Number'), ('INVOICE', 'Commercial Invoice'), ('CERTIFICATE', 'Certificate of Origin')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_documents', to='international.internationalshipment')),
            ],
            options={
                'db_table': 'customs_documents',
            },
        ),
    ]
