# Generated by Django 4.2.10 on 2026-02-20 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalshipment',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assigned_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internationalshipment',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='Set to True when payment webhook received'),
        ),
    ]
